language: ruby

rvm:
- 2.1
script:
  - bundle exec rake test
  - travis_wait bundle exec rake testlinks || true

# Force gh-pages branch to be tested
branches:
  only:
    - /.*/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
  webhooks: http://localhost:55678/travis-ci
  email: false
