language: ruby
sudo: false
cache: bundler

rvm:
- 2.1

script:
  - bundle exec rake test

after_success:
  - bundle exec rake testlinks

# Force gh-pages branch to be tested
branches:
  only:
    - /.*/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
  webhooks: http://146.169.46.217:55678/travis-ci
  email: false
