language: ruby

rvm:
- 2.1
script: travis_wait bundle exec rake test

# Force gh-pages branch to be tested
branches:
  only:
    - /.*/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
  irc:
    channels:
      - "ircs://irc.elvum.net:6697#rr"
    template:
      - "%{repository_name} build %{result} - %{author} %{commit}: %{commit_message} (%{build_url})"
  email: false
