include:
  - _schema
exclude:
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - CNAME

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

github:
    repository_url: "https://github.com/resource-reasoning/resourcereasoning.com"
    issues_url: "https://github.com/resource-reasoning/resourcereasoning.com/issues"

defaults:
  -
    scope:
      path: ""
    values:
      layout: page

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]


prose:
  media: "media"
  ignore:
    - vendor
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - CNAME
    - .gitignore
    - .gitmodules
    - .travis.yml
    - _config.yml
    - _tests
    - _schema
    - edit
