exclude: [vendor,README.md,Gemfile,Gemfile.lock,Rakefile]

gems:
  - jekyll-sitemap

# GitHub will override these
github:
    repository_url: "//github.com/resource-reasoning/resourcereasoning.com"
    issues_url: "//github.com/resource-reasoning/resourcereasoning.com/issues"

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
