include:
  - _schema
exclude: &exclude
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - CNAME

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

github:
    repository_url: "https://github.com/resource-reasoning/resourcereasoning.com"
    issues_url: "https://github.com/resource-reasoning/resourcereasoning.com/issues"

defaults:
  -
    scope:
      path: ""
    values:
      layout: page

prose:
  ignore: << *exclude
    - .gitignore
    - .travis.yml
    - _config.yml
    - _tests
