include:
  - _schema
exclude:
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - CNAME

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

github:
    repository_url: "https://github.com/resource-reasoning/resourcereasoning.com"
    issues_url: "https://github.com/resource-reasoning/resourcereasoning.com/issues"

defaults:
  -
    scope:
      path: ""
    values:
      layout: page

prose:
  ignore:
    - vendor
    - README.md
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - CNAME
    - .gitignore
    - .travis.yml
    - _config.yml
    - _tests
    - _schema
